CREATE TABLE help_queue (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    is_open BOOLEAN NOT NULL DEFAULT FALSE,
    next_number BIGINT NOT NULL DEFAULT 1 CHECK (next_number > 0)
);
INSERT INTO help_queue (id) VALUES (1);

CREATE TABLE staff (
    username VARCHAR(50) PRIMARY KEY,
    password_hash VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen TIMESTAMPTZ
);

CREATE TABLE ticket (
    id UUID PRIMARY KEY,
    queue_id SMALLINT NOT NULL REFERENCES help_queue(id),
    number BIGINT NOT NULL CHECK (number > 0),
    owner UUID NOT NULL,
    display_name VARCHAR(40),
    state VARCHAR(20) NOT NULL CHECK (state IN ('WAITING','CALLED','IN_SERVICE','COMPLETED','CANCELLED','NO_SHOW')),
    assigned_to VARCHAR(50) REFERENCES staff(username),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    called_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    UNIQUE(queue_id, number),
    CHECK ((state IN ('WAITING','CANCELLED') AND assigned_to IS NULL) OR
           (state IN ('CALLED','IN_SERVICE','COMPLETED','NO_SHOW') AND assigned_to IS NOT NULL)),
    CHECK (state NOT IN ('IN_SERVICE','COMPLETED') OR started_at IS NOT NULL),
    CHECK (state NOT IN ('COMPLETED','CANCELLED','NO_SHOW') OR finished_at IS NOT NULL)
);
CREATE UNIQUE INDEX one_student_active ON ticket(queue_id, owner) WHERE state IN ('WAITING','CALLED','IN_SERVICE');
CREATE UNIQUE INDEX one_staff_active ON ticket(assigned_to) WHERE state IN ('CALLED','IN_SERVICE');
CREATE INDEX queue_fifo ON ticket(queue_id, number, id) WHERE state = 'WAITING';
CREATE INDEX ticket_owner ON ticket(owner, number DESC);

CREATE TABLE operation_result (
    caller VARCHAR(80) NOT NULL,
    operation VARCHAR(20) NOT NULL,
    key UUID NOT NULL,
    payload TEXT NOT NULL,
    response TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(caller, operation, key)
);
CREATE TABLE audit_event (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ticket_id UUID REFERENCES ticket(id),
    actor VARCHAR(80) NOT NULL,
    from_state VARCHAR(20),
    to_state VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Spring Session JDBC's PostgreSQL schema, managed by Flyway.
CREATE TABLE SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL PRIMARY KEY,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100)
);
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BYTEA NOT NULL,
    PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME)
);
